In [20]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import csv

In [3]:
cuadrados_uno_once = np.arange(11)**2

In [4]:
cuadrados_uno_once

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [5]:
cuadrados_uno_once[2],cuadrados_uno_once[4],cuadrados_uno_once[6]

(4, 16, 36)

In [6]:
indices = [2,6,8]

In [7]:
cuadrados_uno_once[indices]

array([ 4, 36, 64], dtype=int32)

In [9]:
indice_dos = np.array([[2,4],[8,10]])

In [10]:
indice_dos

array([[ 2,  4],
       [ 8, 10]])

In [12]:
cuadrados_uno_once[indice_dos]

array([[  4,  16],
       [ 64, 100]], dtype=int32)

In [13]:
frutas = np.array([
    ['Pera','Manzana','Banano','Mango'],
    ['Coco','Naranja','Mandarina','Piña'],
    ['Frutilla','Mora','Papaya','Melon']
])

In [14]:
frutas

array([['Pera', 'Manzana', 'Banano', 'Mango'],
       ['Coco', 'Naranja', 'Mandarina', 'Piña'],
       ['Frutilla', 'Mora', 'Papaya', 'Melon']], dtype='<U9')

In [15]:
frutas.shape

(3, 4)

In [17]:
arreglo_filas = np.array([[0,0],[2,2]])  # 0,0 - 0,3 - 2,0 - 2,3
arreglo_columnas = np.array([[0,3],[0,3]])
frutas[arreglo_filas, arreglo_columnas]

array([['Pera', 'Mango'],
       ['Frutilla', 'Melon']], dtype='<U9')

In [18]:
 frutas = np.array([
    ['Pera','Manzana','Banano','Mango'],
    ['Coco','Naranja','Mandarina','Piña'],
    ['Frutilla','Mora','Papaya','Melon']
])
arreglo_filas = np.array([[0,0],[2,2]])  # 0,0 - 0,3 - 2,0 - 2,3
arreglo_columnas = np.array([[0,3],[0,3]])
frutas[arreglo_filas, arreglo_columnas] = 'HHHH'

In [19]:
frutas

array([['HHHH', 'Manzana', 'Banano', 'HHHH'],
       ['Coco', 'Naranja', 'Mandarina', 'Piña'],
       ['HHHH', 'Mora', 'Papaya', 'HHHH']], dtype='<U9')