In [1]:
import numpy as np

In [4]:
matriz = np.arange(16).reshape(4,4)
matriz

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [10]:
indices_mayores_nueve_booleano = matriz > 9
print(np.count_nonzero(indices_mayores_nueve_booleano))
indices_mayores_nueve_booleano

6


array([[False, False, False, False],
       [False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [8]:
matriz[indices_mayores_nueve_booleano]

array([10, 11, 12, 13, 14, 15])

In [15]:
print(matriz > 6)
print(np.sum(matriz > 6))
print(matriz)
np.sum(matriz > 6, axis = 1)  # fila por fila va viendo cuantos se cumplen
# en la primera se cumple 0, segunda 1, tercera todos(4), cuartas todos (4)

[[False False False False]
 [False False False  True]
 [ True  True  True  True]
 [ True  True  True  True]]
9
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


array([0, 1, 4, 4])